### ISSUE TITLE
Provider Not available

### ISSUE THREAD

**Issue by mudasar321** [ictinnovations/ictfax#16]
Hi Guys,

 I've installed new version of ICTFAX. When I try to send fax from "Outbound Fax" it gives me error Provider not found. While I've added a trunk under Provider/Trunks. Please advise

**Comment by vladutz33** [comment]
Hi Guys,
I have the same issue. I think it's a configuration problem but there is little to no documentation on the provider configuration ...

**Comment by tahiralmas** [comment]
Until next update please issue following command against ICTFAX database

UPDATE provider SET service_flag=3 WHERE provider_id=??;

**Comment by vladutz33** [comment]
After applying this to the database it doesn't show the error anymore but it doesn't send the fax either

**Comment by tahiralmas** [comment]
Does it dial?

If not then please check logs /usr/ictcore/log/ictcore.log and /var/logs/httpd/error_log

**Comment by vladutz33** [comment]
I found out what the problem was. ictfax does not automatically generate the provider xml file in /usr/ictcore/etc/freeswitch/sip_profiles/provider/name_of_provider.xml . After I defined it manually it worked. Now I have a problem sending the fax via email, it receives the fax but it doesn't send it via email, and there is nothing is the logs .

**Comment by tahiralmas** [comment]
Please check the logs from /usr/ictcore/log/ictcore.log

**Comment by vladutz33** [comment]
I get a warning Session write fail, and nothing else
