### ISSUE TITLE
Email to fax not working

### ISSUE THREAD

**Issue by ffgghhii** [ictinnovations/ictfax#19]
Hi

I installed ictfax on a new server. 
I am able to send a fax using the web interface.
I would like to be able to use the email to fax feature.
I have followed the guide but am still unable to send a fax when sending an email.
Please could you help me troubleshoot

Thanks!

**Comment by ffgghhii** [comment]
I have not received any response here or from the ticket I opened on your site (as per you chat support - I was told to start a ticket on your website).....

**Comment by ICTKashif** [comment]
Please update ICTCore and run following commands

```
yum update ictcore
cd /usr/ictcore/bin/sendmail
./email_to_fax

```
Then restart send-mail services and check it again

**Comment by herrep** [comment]
After having entered provider details in the ictfax provider section which should result in a SIP registration at our Asterisk-based FreePBX, I realized that no registration takes place at all. Gladly I will provide log files, if I receive directions what needs to be debugged.

**Comment by plochu** [comment]
Please have a look at this issue #20 . I think it could help you.

**Comment by ICTKashif** [comment]
> After having entered provider details in the ictfax provider section which should result in a SIP registration at our Asterisk-based FreePBX, I realized that no registration takes place at all. Gladly I will provide log files, if I receive directions what needs to be debugged.

Please make sure, you have allowed VoIP Traffic for ICTFax server from your PBX server

**Comment by herrep** [comment]
I have already considered issue #20 during installation, as I could not even create a provider within the ICTFAX web frontend. However, after adding the missing package, I verified that the provider setup is stored. Even further, freeswitch is running and tries to establish a connection. But something is wrong within freeswitch.

```
2019-06-21 14:52:12.015098 [ERR] sofia_reg.c:2447 asterisk.patent.de Failed Registration with status Service Unavailable [503]. failure #1568

2019-06-21 14:52:13.015074 [WARNING] sofia_reg.c:505 asterisk.patent.de Failed Registration [503], setting retry to 30 seconds.
```

I want to collect further information from freeswitch, but I cannot do so: freeswitch is not properly configured so that I cannot invoke fs_cli to properly debug.

**Comment by plochu** [comment]
503 response in SIP means that your Freeswitch can't reach provider sip server. As @ICTKashif suggested check if IP traffic is allowed between ICTFax and SIP Provider.

Do you see registration attempts on SIP Provider side?

**Comment by herrep** [comment]
Since I reconfigured freeswitch to use IPv4, I can run fs_cli. However, the problem with failing SIP registration still remains. Please let me know by which commands within fs_cli I can debug the failed SIP registrations.

**Comment by plochu** [comment]
At default settings you will se live all registration attempts. But I prefer to make pcap trace and then analize it with wireshark - you will be able to see complete SIP packet trace.
Here is short manual how to make pcap trace: https://freeswitch.org/confluence/display/FREESWITCH/Packet+Capture

And once more the same question. What do you see on provider side?

**Comment by herrep** [comment]
Unfortunately, no registration messages arrive at provider side. On the provider side, I have already run a PCAP trace to see whether indeed nothing arrives.  This was true.  The pcap trace did not show any message from ictfax/freeswitch.  Clearly, the problem could be tat the internet connection in between blocks the traffic.  On the side of ictfax/freeswitch, I performed the following command to ensure that udp packages can be sent to the provider:

`# nc -z -v -u <here_goes_the_provider_ip> 5064
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to <here_goes_the_provider_ip>:5064.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.05 seconds.
`

Therefore, I am confident that the host on which ictfax/freeswitch is installed, indeed can send UDP packets to the provider.

When I log the registration retries on ictfax/freeswitch, I receive the following output at freeswitch:
`2019-06-25 13:11:55.975502 [NOTICE] sofia_reg.c:448 Registering <here_is_the_provider_hostname>
nua.c:622 nua_register() nua: nua_register: entering
nua_stack.c:529 nua_signal() nua(0x7f8f600211e0): sent signal r_register
nua_stack.c:569 nua_stack_signal() nua(0x7f8f600211e0): recv signal r_register
nua_params.c:480 nua_stack_set_params() nua: nua_stack_set_params: entering
soa.c:403 soa_set_params() soa_set_params(static::0x7f8f7c0014c0, ...) called
nua_dialog.c:338 nua_dialog_usage_add() nua(0x7f8f600211e0): adding register usage
nta.c:4417 nta_leg_tcreate() nta_leg_tcreate(0x7f8f7c0066f0)
nta.c:2665 nta_tpn_by_url() nta: selecting scheme sip
sres_cache.c:272 sres_cache_get() sres_cache_get(0x7f8f7c002e80, A, "<here_is_the_provider_hostname>.") called
sres_cache.c:318 sres_cache_get() sres_cache_get(0x7f8f7c002e80, A, "<here_is_the_provider_hostname>.") returned 1 entries
nta.c:10803 outgoing_query_a() nta: for "<here_is_the_provider_hostname>" query "<here_is_the_provider_hostname>" A (cached)
nta.c:10856 outgoing_answer_a() nta: <here_is_the_provider_hostname>. IN A <here_is_the_provider_ip_address>
tport.c:3257 tport_tsend() tport_tsend(0x7f8f7c004640) tpn = udp/<here_is_the_provider_ip_address>:5064
tport.c:4046 tport_resolve() tport_resolve addrinfo = <here_is_the_provider_ip_address>:5064
tport.c:4680 tport_by_addrinfo() tport_by_addrinfo(0x7f8f7c004640): not found by name udp/<here_is_the_provider_ip_address>:5064
tport.c:3636 tport_send_fatal() tport_vsend(0x7f8f7c004640): Operation not permitted with (s=23 udp/<here_is_the_provider_ip_address>:5064)
tport.c:3492 tport_send_msg() tport_vsend returned -1
nta.c:8496 outgoing_print_tport_error() nta: REGISTER (6176765): Operation not permitted (1) with udp/[<here_is_the_provider_ip_address>]:5064
nta.c:1350 set_timeout() nta: timer set to 32000 ms
nta.c:1348 set_timeout() nta: timer shortened to 5000 ms
nua_stack.c:271 nua_stack_event() nua(0x7f8f600211e0): event r_register 503 Service Unavailable
nua_dialog.c:397 nua_dialog_usage_remove_at() nua(0x7f8f600211e0): removing register usage
nta.c:4470 nta_leg_destroy() nta_leg_destroy(0x7f8f7c0066f0)
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
nua.c:366 nua_handle_magic() nua: nua_handle_magic: entering
2019-06-25 13:11:55.975502 [ERR] sofia_reg.c:2447 <here_is_the_provider_hostname> Failed Registration with status Service Unavailable [503]. failure #13`

Please advise how to interpret the following lines:
`tport.c:4046 tport_resolve() tport_resolve addrinfo = <here_is_the_provider_ip_address>:5064
tport.c:4680 tport_by_addrinfo() tport_by_addrinfo(0x7f8f7c004640): not found by name udp/<here_is_the_provider_ip_address>:5064
tport.c:3636 tport_send_fatal() tport_vsend(0x7f8f7c004640): Operation not permitted with (s=23 udp/<here_is_the_provider_ip_address>:5064)
tport.c:3492 tport_send_msg() tport_vsend returned -1
nta.c:8496 outgoing_print_tport_error() nta: REGISTER (6176765): Operation not permitted (1) with udp/[<here_is_the_provider_ip_address>]:5064`

I rather assume that the registration message does not even leave the freeswitch because of "not found" and "not permitted".  Please advise as how to further proceed.

Thank you very much.

Best regards,
Peter

**Comment by plochu** [comment]
A lot of data... but it is hard to guess what is your problem. You just showed sofia debug. You need to see what is in SIP TRACE - the answer is in SIP INVITE or SIP OPTIONS messages.
Using `fs_cli` turn on sip trace `sofia profile external siptrace on` and increase log level `sofia loglevel all 9`

Look at SIP messages, there must be an answer.
Just guessing but are sure that your VoIP provider doesn't use 3-way authentication? I think that ICTfax is not able to handle it.

BTW. I can provide you for test SIP account on my IP PBX that I'm 100% works fine :) just send me an e-mail... you can find it here https://github.com/it-ploch

**Comment by herrep** [comment]
The messages
- tport.c:4046 tport_resolve() tport_resolve addrinfo = <here_is_the_provider_ip_address>:5064
- tport.c:4680 tport_by_addrinfo() tport_by_addrinfo(0x7f8f7c004640): not found by name udp/<here_is_the_provider_ip_address>:5064
- tport.c:3636 tport_send_fatal() tport_vsend(0x7f8f7c004640): Operation not permitted with (s=23 udp/<here_is_the_provider_ip_address>:5064)
- tport.c:3492 tport_send_msg() tport_vsend returned -1
rather indicate that even the sending of the message fails, without considering a particular content like REGISTER. Or am I wrong?

Thank you very much for your offer to try a test SIP account. I will write you an email. Much appreciated!
